name: ElytrixParadise
version: 1.0.1
main: ru.rooyzee.elytrixparadise.Main
api-version: 1.16
author: rooyzee
description: Paradise Cloud Schematic Spawner at X=0, Y=130, Z=0
depend: [WorldEdit]
softdepend: [WorldGuard, DecentHolograms, PlaceholderAPI, FastAsyncWorldEdit]

commands:
  elytrixparadise:
    description: Основная команда управления плагином ElytrixParadise
    aliases: [paradise, ep]
    usage: /elytrixparadise help
    permission: elytrixparadise.use

permissions:
  elytrixparadise.use:
    description: Доступ к базовым командам (/ep help, /ep info, /ep schem)
    default: true
  elytrixparadise.tp:
    description: Доступ к телепортации в Рай (/ep tp)
    default: true
  elytrixparadise.admin:
    description: Полный доступ администратора ко всем командам (/ep reload, /ep paste, /ep setcenter, /ep setspawn)
    default: op
